---
name: Text-xSV-Slurp
version: 0.20
author:
  - 'Dan Boorstein <dan@boorstein.net>'
abstract: Convert xSV data to common data shapes.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  IO::String: 0
  Test::More: 0
  Text::CSV: 0
provides:
  Text::xSV::Slurp:
    file: lib/Text/xSV/Slurp.pm
    version: 0.20
generated_by: Module::Build version 0.280802
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
